[package]
name = "yew-shared"
version = "0.7.0"

[lib]

[dependencies]
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.1"
anymap = "0.12"
slab = "0.4"
stdweb = "^0.4.14"

[target.'cfg(all(target_arch = "wasm32", not(cargo_web)))'.dependencies]
wasm-bindgen = "0.2"
